[Keyboard] gBoards GergoPlex (#13027)
* Moved gergoplex to seperate PR

* vendor + cformat

* Update keyboards/gboards/k/gergoplex/matrix.c

Co-Authored-By: Drashna Jaelre <drashna@live.com>

* lifiting keyboards up

* Update readme.md

* Update keyboards/gboards/gergoplex/config.h

Co-authored-by: Drashna Jaelre <drashna@live.com>

* remove English dicts

* cformatted

* Prettify keymap

* Remove via keymaps

Via doesn't support chords/combos, and this makes the keymap on such a
small keyboard quite uncomfortable and incomplete.

* Address QMK pull code review notes

* Cleanup (tabs, excessive comments)

* Fix keymap typos

* Use enum to define layers

* Multiple changes

 - got rid of LAYOUT_kc in favour of LAYOUT_split_3x5_3
 - fixed matrix custom C code to build with updated external dependencies (gcc)
 - fixed used combo docs

    keyboards/gboards/gergoplex/matrix.c:189:9: error: implicit declaration of function 'phex' [-Werror=implicit-function-declaration]
             phex(row);
             ^~~~
    keyboards/gboards/gergoplex/matrix.c:191:9: error: implicit declaration of function 'pbin_reverse16'; did you mean 'print_bin_reverse16'? [-Werror=implicit-function-declaration]
             pbin_reverse16(matrix_get_row(row));

* Remove apparently redundant macros

* Replace direct pin control with IO functions

* config mouse enable and combo delay fix

The default delay is 200:

    #define COMBO_TERM 200
        how long for the Combo keys to be detected. Defaults to TAPPING_TERM if not defined.

    tmk_core/common/action_tapping.h|22| 13:#    define TAPPING_TERM 200

* Remove redundant defines

* Unambiguously refer to the Special layer

* Fix formatting

* gboards/gergoplex set IGNORE_MOD_TAP_INTERRUPT

This solves my issue was with KC_CTL_A working correctly and it was set in @germ's repo
https://github.com/germ/qmk_firmware/blob/39c86e080dc04b68ee08387dcb5144c88cb44855/keyboards/gboards/k/gergoplex/config.h#L49

 https://beta.docs.qmk.fm/using-qmk/software-features/tap_hold#ignore-mod-tap-interrupt

* Name change

See commit d6879fbba33

* Wording change

* Update keyboards/gboards/gergoplex/keymaps/default/keymap.c

Co-authored-by: Drashna Jaelre <drashna@live.com>

* Add copyright headers

* Fix debounce type

 | avr-gcc: error: .build/obj_gboards_gergoplex_default/quantum/debounce/eager_pr.o: No such file or directory

* Implement colemak-dhm keymap

Co-authored-by: Germ <jeremythegeek@gmail.com>
Co-authored-by: Drashna Jaelre <drashna@live.com>
Co-authored-by: Brian Tannous <Brian@BrianTannous.com>